Table Governors {
  id int
  active boolean
  name varchar 
}

Table Colonies {
  id integer [primary key]
  name varchar
  governorId int [ref: > Governors.id]
}

Table ColonyInventory {
  id int [pk]
  colonyId int [ref: > Colonies.id]
  mineralId int [ref: > Minerals.id ]
  tons int
}


Table MiningFacilities {
  id integer [primary key]
  names varchar
  active boolean
}

Table Minerals {
  id int [pk]
  name varchar

}

Table FacilityInventory {
id int [pk]
mineralId int [ref: > Minerals.id]
miningFacilityId int [ref: > MiningFacilities.id]
tons int
}


