Table Governors {
  id int
  active boolean
  name varchar 
}

Table Colonies {
  id integer [primary key]
  name varchar
  governor_id int [ref: > Governors.id]
}

Table Colony_Inventory {
  id int [pk]
  colony_id int [ref: > Colonies.id]
  mineral_id int [ref: > Minerals.id ]
  tons int
}


Table mining_facilities {
  id integer [primary key]
  names varchar
  active boolean
}

Table Minerals {
  id int [pk]
  name varchar

}

Table Facility_Inventory {
id int [pk]
mineral_id int [ref: > Minerals.id]
mining_facility_id int [ref: > mining_facilities.id]
tons int
}


