sequenceDiagram
title Exomine 

participant User
participant main
participant Governors.js
participant Facilities.js
participant ColonyInventory.js
participant FacilityInventory.js
participant SpaceCart.js
participant PurchaseButton.js
participant TransientState.js
participant database.js

main->>Governors.js: requests governors list
Governors.js ->> database.js: give me the governors data
database.js -->> Governors.js: here is the governors data
loop
note over Governors.js: loop over governors data to <br> create a dropdown menu <br> of governors names
end
Governors.js -->> main: here is the governors list

main->>Facilities.js: request facilities list
Facilities.js ->> database.js: give me the Facilities data
database.js -->> Facilities.js: here is the Facilities data
loop
note over Facilities.js: loop over Facilities data to <br> create a dropdown menu <br> of Facilities names
end
Facilities.js -->> main: here is the facilities list

main->>ColonyInventory.js: request initial colony minerals HTML
ColonyInventory.js -->> main: here is the colony minerals HTML

main->>FacilityInventory.js: request facility minerals HTML
FacilityInventory.js -->> main: here is the facility minerals HTML

main->>SpaceCart.js: request spaceCart HTML
SpaceCart.js ->> PurchaseButton.js: give me button HTML
PurchaseButton.js -->> SpaceCart.js: here is button HTML
SpaceCart.js -->> main: here is the spaceCart HTML

User->>Governors.js: select governor
Governors.js->>ColonyInventory.js: set active governor & colony
ColonyInventory.js ->> database.js: give me colony inventory
database.js -->> ColonyInventory.js: here is the colony inventory
loop
    note over ColonyInventory.js: loop over colony inventory <br> match Colonies governorId <br> with Governors id

end
ColonyInventory.js ->> TransientState.js: set colonyId to the colonies id
TransientState.js -->> ColonyInventory.js: done
loop
    note over ColonyInventory.js:loop over matched colonyInventory<br> To get the minerals and<br> create HTML
end
ColonyInventory.js ->> Facilities.js: enable the select option
Facilities.js -->> ColonyInventory.js: ok
ColonyInventory.js -->> main:The colony was selected

note over main: renders the selected inventory


User->>Facilities.js: select facility
Facilities.js ->> TransientState.js: update selected facility id
TransientState.js -->> Facilities.js: updated
Facilities.js->>FacilityInventory.js: A facility was picked get me that info
FacilityInventory.js ->> database.js: give me facility inventory data
database.js -->> FacilityInventory.js: here is the facility inventory data
loop
    note over FacilityInventory.js:loop over facilityInventory data<br> match miningFacilityId to miningFacilities id

end
loop
    note over FacilityInventory.js: loop over selected<br> get minerals that match<br> the facility<br> and create HTML if > 0
end
FacilityInventory.js -->> main: facility Inventory has been selected, re render
note over main: re render

User->>FacilityInventory.js: add mineral to cart
FacilityInventory.js ->> TransientState.js: update transient state with mineral id
note over TransientState.js: set facilityInventory tons to current tons - 1<br> set ColonyInventory tons to current + 1<br> use fetch expanded to get tons
loop
    note over TransientState.js: loop over facilityInventory Expanded

    alt FacilityInventory id is === miningFacilityId
        note over TransientState.js: get tons and subtract 1<br>  add that to transient state for facilities inventory
    end
 
end
loop
    note over TransientState.js: loop over colonyInventory Expanded<br>

    alt colonyId is === Colonies id
        note over TransientState.js: get tons and add 1<br> add that to transient state for colony inventory and store ColonyInventory id as a variable
    end
 
end
TransientState.js -->> FacilityInventory.js: updated
FacilityInventory.js ->> SpaceCart.js: We selected an option
SpaceCart.js ->> TransientState.js: give me that shit RN
TransientState.js -->> SpaceCart.js: Sure.
SpaceCart.js ->> database.js: give me facilityInventory expanded
database.js -->> SpaceCart.js: here ya go
loop
    note over SpaceCart.js: loop over expanded facilityInventory data <br> get facility name<br> get mineral name<br> generate HTML <br> store FacilityInventory id in a variable
end
SpaceCart.js -->> main: cart was updated
note over main: re render



User ->> PurchaseButton.js: clicks purchase
PurchaseButton.js -->> TransientState.js: update database 1 ton added to colonyInventory<br> 1 ton removed from chosen facility
TransientState.js ->> database.js: updates the database with transient info.
database.js -->> TransientState.js: done
TransientState.js -->> main: database has changed

note over main: re render